// Mock Products Data - All Categories with Unique Images

export const mockProducts = {
  // ============================================================
  // 1. HAIRS - 20 Unique Products
  // ============================================================
  'Hairs': [
    {
      _id: 'hair-001',
      name: 'Brazilian Body Wave Human Hair',
      description: 'Premium 100% human hair, body wave texture, 16 inches, 3 bundles. Soft, tangle-free, and long-lasting.',
      price: 45000,
      stock: 15,
      sku: 'HR-001',
      images: ['https://images.unsplash.com/photo-1525130413817-d45c1d127c42?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'hair-002',
      name: 'Peruvian Straight Hair Bundle',
      description: 'Luxury Peruvian straight hair, 14 inches, 4 bundles with closure. Silky smooth and easy to style.',
      price: 52000,
      stock: 12,
      sku: 'HR-002',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'hair-003',
      name: 'Malaysian Curly Hair',
      description: 'Beautiful Malaysian curly hair, 18 inches, natural curl pattern. Perfect for a voluminous look.',
      price: 48000,
      stock: 20,
      sku: 'HR-003',
      images: ['https://images.unsplash.com/photo-1519415387722-a1c3bbef9e54?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-004',
      name: 'Bone Straight Human Hair',
      description: 'Silky bone straight human hair, 20 inches, tangle-free and sheds minimally.',
      price: 55000,
      stock: 10,
      sku: 'HR-004',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-005',
      name: 'Deep Wave Hair Bundles',
      description: 'Deep wave texture human hair, 22 inches, 3 bundles. Full and bouncy curls.',
      price: 58000,
      stock: 8,
      sku: 'HR-005',
      images: ['https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-006',
      name: 'Water Wave Human Hair',
      description: 'Natural water wave hair, 16 inches, 4 bundles. Perfect for a beachy wave look.',
      price: 49000,
      stock: 18,
      sku: 'HR-006',
      images: ['https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-007',
      name: 'Kinky Straight Hair',
      description: 'Kinky straight human hair, 14 inches, 3 bundles. Natural texture for a relaxed look.',
      price: 42000,
      stock: 22,
      sku: 'HR-007',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-008',
      name: 'Loose Wave Hair Extensions',
      description: 'Loose wave texture, 18 inches, 2 bundles with closure. Natural and elegant waves.',
      price: 47000,
      stock: 14,
      sku: 'HR-008',
      images: ['https://images.unsplash.com/photo-1525130413817-d45c1d127c42?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-009',
      name: 'Natural Black Straight Hair',
      description: 'Natural black straight hair, 20 inches, 3 bundles. Classic and versatile.',
      price: 43000,
      stock: 16,
      sku: 'HR-009',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-010',
      name: 'Ombre Hair Extensions',
      description: 'Beautiful ombre hair, 22 inches, brown to blonde. Stunning gradient color.',
      price: 62000,
      stock: 7,
      sku: 'HR-010',
      images: ['https://images.unsplash.com/photo-1519415387722-a1c3bbef9e54?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'hair-011',
      name: 'HD Lace Closure',
      description: 'High-definition lace closure, 4x4 inches, invisible lace. Perfect for natural hairlines.',
      price: 35000,
      stock: 25,
      sku: 'HR-011',
      images: ['https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-012',
      name: 'Lace Frontal Wig',
      description: 'Full lace frontal wig, 13x4 inches, pre-plucked. Natural hairline with baby hair.',
      price: 68000,
      stock: 5,
      sku: 'HR-012',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'hair-013',
      name: 'Ponytail Extension',
      description: 'Natural looking ponytail extension, 18 inches. Easy to install and secure.',
      price: 25000,
      stock: 30,
      sku: 'HR-013',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-014',
      name: 'Colored Hair Bundles',
      description: 'Colored hair bundles, burgundy color, 16 inches. Vibrant and bold.',
      price: 48000,
      stock: 12,
      sku: 'HR-014',
      images: ['https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-015',
      name: 'Blonde Straight Hair',
      description: 'Platinum blonde straight hair, 20 inches. Stunning and eye-catching.',
      price: 58000,
      stock: 8,
      sku: 'HR-015',
      images: ['https://images.unsplash.com/photo-1525130413817-d45c1d127c42?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-016',
      name: 'Brazilian Curly Hair',
      description: 'Brazilian curly hair, 14 inches, 3 bundles. Beautiful bouncy curls.',
      price: 50000,
      stock: 15,
      sku: 'HR-016',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-017',
      name: 'Peruvian Body Wave',
      description: 'Peruvian body wave hair, 18 inches, 4 bundles. Soft and manageable waves.',
      price: 53000,
      stock: 10,
      sku: 'HR-017',
      images: ['https://images.unsplash.com/photo-1519415387722-a1c3bbef9e54?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-018',
      name: 'Malaysian Straight Hair',
      description: 'Malaysian straight hair, 16 inches, 3 bundles. Silky and lightweight.',
      price: 46000,
      stock: 20,
      sku: 'HR-018',
      images: ['https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-019',
      name: 'Deep Curl Hair',
      description: 'Deep curl human hair, 20 inches, 2 bundles. Defined and long-lasting curls.',
      price: 52000,
      stock: 9,
      sku: 'HR-019',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hair-020',
      name: 'Body Wave Hair',
      description: 'Body wave human hair, 16 inches, 3 bundles. Perfect for any occasion.',
      price: 44000,
      stock: 25,
      sku: 'HR-020',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat1', name: 'Hairs', slug: 'hairs' },
      featured: false,
      status: 'active',
    },
  ],

  // ============================================================
  // 2. HAIR PRODUCTS - 20 Unique Products
  // ============================================================
  'Hair Products': [
    {
      _id: 'hp-001',
      name: 'Professional Shampoo Set',
      description: 'Professional hair shampoo with argan oil. Deeply cleanses and nourishes all hair types.',
      price: 8500,
      stock: 40,
      sku: 'HP-001',
      images: ['https://images.unsplash.com/photo-1522337362445-01b88a8f4e0c?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'hp-002',
      name: 'Hair Conditioner',
      description: 'Deep conditioning treatment for all hair types. Restores moisture and shine.',
      price: 7500,
      stock: 35,
      sku: 'HP-002',
      images: ['https://images.unsplash.com/photo-1582333388877-51fe5a2fde3e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-003',
      name: 'Hair Relaxer Cream',
      description: 'Gentle hair relaxer for smooth straight hair. Safe and effective formula.',
      price: 12000,
      stock: 20,
      sku: 'HP-003',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-004',
      name: 'Edge Control Gel',
      description: 'Strong hold edge control gel. Keeps edges sleek and smooth all day.',
      price: 3500,
      stock: 50,
      sku: 'HP-004',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-005',
      name: 'Hair Moisturizer',
      description: 'Daily hair moisturizer with shea butter. Keeps hair hydrated and soft.',
      price: 4500,
      stock: 45,
      sku: 'HP-005',
      images: ['https://images.unsplash.com/photo-1522337362445-01b88a8f4e0c?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-006',
      name: 'Argan Oil Treatment',
      description: 'Pure Moroccan argan oil for hair repair. Restores damaged hair.',
      price: 8000,
      stock: 30,
      sku: 'HP-006',
      images: ['https://images.unsplash.com/photo-1582333388877-51fe5a2fde3e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'hp-007',
      name: 'Hair Growth Serum',
      description: 'Advanced hair growth serum with biotin. Promotes healthy hair growth.',
      price: 15000,
      stock: 18,
      sku: 'HP-007',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-008',
      name: 'Hair Wax Stick',
      description: 'Hair styling wax stick for edges, 50g. Provides strong hold and shine.',
      price: 2500,
      stock: 60,
      sku: 'HP-008',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-009',
      name: 'Hair Spray Strong Hold',
      description: 'Strong hold hairspray, 300ml. Long-lasting hold for all styles.',
      price: 5500,
      stock: 40,
      sku: 'HP-009',
      images: ['https://images.unsplash.com/photo-1522337362445-01b88a8f4e0c?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-010',
      name: 'Coconut Oil Hair Mask',
      description: 'Deep conditioning hair mask with coconut oil. Repairs and nourishes dry hair.',
      price: 6500,
      stock: 25,
      sku: 'HP-010',
      images: ['https://images.unsplash.com/photo-1582333388877-51fe5a2fde3e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-011',
      name: 'Hair Dye Cream',
      description: 'Permanent hair color cream, various shades, 150ml. Long-lasting rich color.',
      price: 7000,
      stock: 35,
      sku: 'HP-011',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-012',
      name: 'Hair Bleach Powder',
      description: 'Professional hair bleach powder, 500g. For lightening and highlighting.',
      price: 9000,
      stock: 20,
      sku: 'HP-012',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-013',
      name: 'Hair Developer Cream',
      description: 'Hair developer cream for dyeing, 1L. Professional strength for even color.',
      price: 6000,
      stock: 25,
      sku: 'HP-013',
      images: ['https://images.unsplash.com/photo-1522337362445-01b88a8f4e0c?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-014',
      name: 'Hair Heat Protectant',
      description: 'Heat protectant spray for styling, 200ml. Protects hair from heat damage.',
      price: 4500,
      stock: 30,
      sku: 'HP-014',
      images: ['https://images.unsplash.com/photo-1582333388877-51fe5a2fde3e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-015',
      name: 'Hair Gel Strong Hold',
      description: 'Strong hold styling gel, 300ml. Provides maximum hold and control.',
      price: 3500,
      stock: 50,
      sku: 'HP-015',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-016',
      name: 'Hair Mousse',
      description: 'Volumizing hair mousse for full body. Adds volume and bounce to hair.',
      price: 5000,
      stock: 28,
      sku: 'HP-016',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-017',
      name: 'Jamaican Black Castor Oil',
      description: 'Jamaican black castor oil for hair growth, 250ml. Promotes healthy hair growth.',
      price: 7000,
      stock: 22,
      sku: 'HP-017',
      images: ['https://images.unsplash.com/photo-1522337362445-01b88a8f4e0c?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-018',
      name: 'Hair Shine Serum',
      description: 'Hair shine serum with vitamin E, 100ml. Adds brilliant shine to dull hair.',
      price: 4000,
      stock: 35,
      sku: 'HP-018',
      images: ['https://images.unsplash.com/photo-1582333388877-51fe5a2fde3e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-019',
      name: 'Leave-in Conditioner',
      description: 'Leave-in conditioner spray for daily care, 250ml. Detangles and softens hair.',
      price: 5500,
      stock: 40,
      sku: 'HP-019',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'hp-020',
      name: 'Hair Color Remover',
      description: 'Safe hair color remover, 200ml. Gently removes unwanted hair color.',
      price: 8000,
      stock: 15,
      sku: 'HP-020',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat2', name: 'Hair Products', slug: 'hair-products' },
      featured: false,
      status: 'active',
    },
  ],

  // ============================================================
  // 3. SALON MATERIALS - 20 Unique Products
  // ============================================================
  'Salon Materials': [
    {
      _id: 'sm-001',
      name: 'Professional Hair Cutting Scissors',
      description: 'Stainless steel professional hair cutting shears. Precision sharp blades for perfect cuts.',
      price: 18000,
      stock: 15,
      sku: 'SM-001',
      images: ['https://images.unsplash.com/photo-1595698199523-2c54f99aa262?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'sm-002',
      name: 'Neck Strips Disposable',
      description: 'Disposable neck strips for salon use, 500 pieces. Hygienic and comfortable for clients.',
      price: 2500,
      stock: 50,
      sku: 'SM-002',
      images: ['https://images.unsplash.com/photo-1631561066360-4055ec316dfe?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-003',
      name: 'Barber Cape Professional',
      description: 'Professional barber cape with adjustable closure. Water-resistant and durable material.',
      price: 4000,
      stock: 30,
      sku: 'SM-003',
      images: ['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-004',
      name: 'Hair Cutting Comb Set',
      description: 'Professional hair cutting comb set, 5 pieces. Various sizes for precision cutting.',
      price: 3000,
      stock: 40,
      sku: 'SM-004',
      images: ['https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-005',
      name: 'Barber Clipper Oil',
      description: 'Professional clipper oil, 100ml. Keeps clippers running smoothly and extends blade life.',
      price: 2000,
      stock: 45,
      sku: 'SM-005',
      images: ['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-006',
      name: 'Hair Cutting Cape',
      description: 'Waterproof hair cutting cape with snaps. Easy to clean and durable for daily salon use.',
      price: 3500,
      stock: 25,
      sku: 'SM-006',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-007',
      name: 'Hair Cutting Balancing Blocks',
      description: 'Hair cutting balancing blocks for men, 5x5cm. Provides even cutting surface for precision.',
      price: 1500,
      stock: 50,
      sku: 'SM-007',
      images: ['https://images.unsplash.com/photo-1595698199523-2c54f99aa262?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-008',
      name: 'Foil Paper for Hair Dyeing',
      description: 'Professional hair dyeing foil paper, 500 sheets. Perfect for highlighting and color techniques.',
      price: 2000,
      stock: 35,
      sku: 'SM-008',
      images: ['https://images.unsplash.com/photo-1631561066360-4055ec316dfe?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-009',
      name: 'Tint Brush Set',
      description: 'Professional hair tint brush, 4 pieces. Durable and easy to clean for color application.',
      price: 2500,
      stock: 40,
      sku: 'SM-009',
      images: ['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-010',
      name: 'Mixing Bowl Set',
      description: 'Professional mixing bowl set for color processing. Stain-resistant and easy to clean.',
      price: 3000,
      stock: 30,
      sku: 'SM-010',
      images: ['https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-011',
      name: 'Spatula for Hair Color',
      description: 'Professional mixing spatula for hair color, 5 pieces. Precise mixing and application.',
      price: 1500,
      stock: 45,
      sku: 'SM-011',
      images: ['https://images.unsplash.com/photo-1595698199523-2c54f99aa262?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-012',
      name: 'Ear Guards for Barbers',
      description: 'Barber ear guards for safety, 5 pieces. Protects clients during hair cutting.',
      price: 2000,
      stock: 50,
      sku: 'SM-012',
      images: ['https://images.unsplash.com/photo-1631561066360-4055ec316dfe?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-013',
      name: 'Hair Sectioning Clips',
      description: 'Professional hair sectioning clips, 24 pieces. Keeps hair secure during cutting and styling.',
      price: 2500,
      stock: 40,
      sku: 'SM-013',
      images: ['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-014',
      name: 'Tail Comb Professional',
      description: 'Professional tail comb for precision sectioning and styling. Fine-tooth for detailed work.',
      price: 1500,
      stock: 50,
      sku: 'SM-014',
      images: ['https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-015',
      name: 'Widening Comb',
      description: 'Professional widening comb for volume and texture. Creates natural-looking results.',
      price: 2000,
      stock: 35,
      sku: 'SM-015',
      images: ['https://images.unsplash.com/photo-1595698199523-2c54f99aa262?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-016',
      name: 'Hair Pin Set',
      description: 'Professional hair pin set, 50 pieces. Strong hold for all hair types and styles.',
      price: 1500,
      stock: 45,
      sku: 'SM-016',
      images: ['https://images.unsplash.com/photo-1631561066360-4055ec316dfe?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-017',
      name: 'Bobby Pins Set',
      description: 'Professional bobby pins set, 100 pieces. Essential for styling and updos.',
      price: 1000,
      stock: 60,
      sku: 'SM-017',
      images: ['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-018',
      name: 'Duckbill Clips',
      description: 'Professional duckbill clips for sectioning, 12 pieces. Secure hold with easy release.',
      price: 2000,
      stock: 40,
      sku: 'SM-018',
      images: ['https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-019',
      name: 'Hair Foam Rollers',
      description: 'Professional hair foam rollers set, 12 pieces. Creates beautiful curls and waves.',
      price: 2500,
      stock: 30,
      sku: 'SM-019',
      images: ['https://images.unsplash.com/photo-1595698199523-2c54f99aa262?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'sm-020',
      name: 'Wide Tooth Comb',
      description: 'Professional wide tooth comb for detangling. Gentle on all hair types.',
      price: 1500,
      stock: 50,
      sku: 'SM-020',
      images: ['https://images.unsplash.com/photo-1631561066360-4055ec316dfe?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials' },
      featured: false,
      status: 'active',
    },
  ],

  // ============================================================
  // 4. SALON EQUIPMENT - 20 Unique Products
  // ============================================================
  'Salon Equipment': [
    {
      _id: 'eq-001',
      name: 'Professional Hair Dryer',
      description: 'Ionic professional hair dryer with diffuser, 2000W. Fast drying with less damage.',
      price: 35000,
      stock: 12,
      sku: 'EQ-001',
      images: ['https://images.unsplash.com/photo-1519415387722-a1c3bbef9e54?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'eq-002',
      name: 'Hair Straightener',
      description: 'Professional ceramic hair straightener, adjustable temperature. Smooth results without damage.',
      price: 28000,
      stock: 15,
      sku: 'EQ-002',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-003',
      name: 'Curling Wand',
      description: 'Professional curling wand, 1-inch barrel, with gloves. Creates beautiful, long-lasting curls.',
      price: 25000,
      stock: 10,
      sku: 'EQ-003',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-004',
      name: 'Salon Hair Steamer',
      description: 'Professional hair steamer for deep conditioning. Penetrates moisture into the hair shaft.',
      price: 85000,
      stock: 5,
      sku: 'EQ-004',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'eq-005',
      name: 'Hooded Hair Dryer',
      description: 'Hooded hair dryer for salon use, adjustable height. Professional drying for all hair types.',
      price: 45000,
      stock: 8,
      sku: 'EQ-005',
      images: ['https://images.unsplash.com/photo-1519415387722-a1c3bbef9e54?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-006',
      name: 'Professional Clipper Set',
      description: 'Complete professional clipper set with attachments. Powerful motor for smooth cutting.',
      price: 55000,
      stock: 10,
      sku: 'EQ-006',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-007',
      name: 'Hair Trimmer',
      description: 'Professional hair trimmer for edges, cordless. Precision trimming for clean lines.',
      price: 30000,
      stock: 15,
      sku: 'EQ-007',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-008',
      name: 'Salon Chair',
      description: 'Professional salon styling chair, hydraulic. Comfortable and adjustable for clients.',
      price: 120000,
      stock: 4,
      sku: 'EQ-008',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-009',
      name: 'Shampoo Station',
      description: 'Professional shampoo station with basin. Comfortable design for client relaxation.',
      price: 150000,
      stock: 3,
      sku: 'EQ-009',
      images: ['https://images.unsplash.com/photo-1519415387722-a1c3bbef9e54?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-010',
      name: 'Hair Dryer Stand',
      description: 'Adjustable hair dryer stand for salon. Convenient and space-saving design.',
      price: 18000,
      stock: 12,
      sku: 'EQ-010',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-011',
      name: 'Curling Iron Set',
      description: 'Professional curling iron set, 3 sizes. Versatile for creating various curl styles.',
      price: 32000,
      stock: 8,
      sku: 'EQ-011',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-012',
      name: 'Hot Air Brush',
      description: 'Professional hot air styling brush. Smooths and dries hair simultaneously.',
      price: 22000,
      stock: 10,
      sku: 'EQ-012',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-013',
      name: 'Barber Chair',
      description: 'Professional barber chair with footrest. Classic design with smooth operation.',
      price: 130000,
      stock: 5,
      sku: 'EQ-013',
      images: ['https://images.unsplash.com/photo-1519415387722-a1c3bbef9e54?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-014',
      name: 'Hair Dryer Wall Mount',
      description: 'Wall mount for hair dryer, adjustable. Keeps dryer accessible and saves counter space.',
      price: 15000,
      stock: 15,
      sku: 'EQ-014',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-015',
      name: 'Professional Mirror with Lights',
      description: 'Professional salon mirror with built-in LED lights. Perfect for precise styling.',
      price: 40000,
      stock: 8,
      sku: 'EQ-015',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-016',
      name: 'Hair Dryer Diffuser',
      description: 'Professional hair dryer diffuser attachment. Creates defined curls and adds volume.',
      price: 8000,
      stock: 20,
      sku: 'EQ-016',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-017',
      name: 'Curling Iron Holder',
      description: 'Heat resistant curling iron holder. Safe storage for hot styling tools.',
      price: 10000,
      stock: 15,
      sku: 'EQ-017',
      images: ['https://images.unsplash.com/photo-1519415387722-a1c3bbef9e54?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-018',
      name: 'Hot Comb',
      description: 'Professional hot comb for pressing and straightening. Traditional tool with modern heating.',
      price: 15000,
      stock: 10,
      sku: 'EQ-018',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-019',
      name: 'Salon Trolley',
      description: 'Professional salon trolley for tools. Mobile storage with multiple compartments.',
      price: 35000,
      stock: 6,
      sku: 'EQ-019',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'eq-020',
      name: 'Professional Hot Brush',
      description: 'Professional hot brush for styling. Heated bristles for smooth, frizz-free results.',
      price: 25000,
      stock: 10,
      sku: 'EQ-020',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment' },
      featured: false,
      status: 'active',
    },
  ],

  // ============================================================
  // 5. NAILS & ACCESSORIES - 20 Unique Products
  // ============================================================
  'Nails & Accessories': [
    {
      _id: 'nl-001',
      name: 'Professional Nail Kit',
      description: 'Complete professional nail kit with essential tools. Perfect for manicures and pedicures.',
      price: 18000,
      stock: 20,
      sku: 'NL-001',
      images: ['https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'nl-002',
      name: 'Acrylic Nail Powder',
      description: 'Professional acrylic nail powder, 100g. Creates strong, durable nail extensions.',
      price: 8000,
      stock: 25,
      sku: 'NL-002',
      images: ['https://images.unsplash.com/photo-1596460107916-4506628f5b7e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-003',
      name: 'Nail Polish Collection',
      description: '48-piece nail polish collection, various colors. High-quality, long-lasting formula.',
      price: 45000,
      stock: 15,
      sku: 'NL-003',
      images: ['https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'nl-004',
      name: 'UV Nail Lamp',
      description: 'Professional UV LED nail lamp for curing. Fast drying with powerful bulbs.',
      price: 25000,
      stock: 18,
      sku: 'NL-004',
      images: ['https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-005',
      name: 'Nail File Set',
      description: 'Professional nail file set, 10 pieces. Various grits for perfect nail shaping.',
      price: 5000,
      stock: 40,
      sku: 'NL-005',
      images: ['https://images.unsplash.com/photo-1596460107916-4506628f5b7e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-006',
      name: 'Gel Nail Polish',
      description: 'Professional gel nail polish, 36 colors. High-gloss, chip-resistant formula.',
      price: 32000,
      stock: 12,
      sku: 'NL-006',
      images: ['https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-007',
      name: 'Nail Art Brush Set',
      description: 'Professional nail art brush set, 12 pieces. Precision brushes for detailed designs.',
      price: 8000,
      stock: 30,
      sku: 'NL-007',
      images: ['https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-008',
      name: 'Nail Glue',
      description: 'Professional nail glue for tips, 50ml. Strong, long-lasting adhesive for nail applications.',
      price: 3000,
      stock: 45,
      sku: 'NL-008',
      images: ['https://images.unsplash.com/photo-1596460107916-4506628f5b7e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-009',
      name: 'Nail Tips',
      description: 'Professional nail tips, 500 pieces, various sizes. Pre-shaped for perfect extensions.',
      price: 6000,
      stock: 35,
      sku: 'NL-009',
      images: ['https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-010',
      name: 'Nail Buffer Block',
      description: 'Professional nail buffer block set. Creates high-shine finish on natural nails.',
      price: 2500,
      stock: 50,
      sku: 'NL-010',
      images: ['https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-011',
      name: 'Cuticle Pusher Set',
      description: 'Professional cuticle pusher set, 5 pieces. Gently pushes back cuticles for neat nails.',
      price: 3000,
      stock: 40,
      sku: 'NL-011',
      images: ['https://images.unsplash.com/photo-1596460107916-4506628f5b7e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-012',
      name: 'Nail Clipper Set',
      description: 'Professional nail clipper set with case. Precision cutting for all nail types.',
      price: 4000,
      stock: 35,
      sku: 'NL-012',
      images: ['https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-013',
      name: 'Nail Polish Remover',
      description: 'Professional nail polish remover, 500ml. Gently removes all types of nail polish.',
      price: 3500,
      stock: 40,
      sku: 'NL-013',
      images: ['https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-014',
      name: 'Nail Decoration Set',
      description: 'Nail art decoration set, 100+ pieces. Includes rhinestones, glitter, and charms.',
      price: 5000,
      stock: 30,
      sku: 'NL-014',
      images: ['https://images.unsplash.com/photo-1596460107916-4506628f5b7e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-015',
      name: 'Nail Drill Machine',
      description: 'Professional electric nail drill with bits. Perfect for filing, shaping, and buffing.',
      price: 35000,
      stock: 10,
      sku: 'NL-015',
      images: ['https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-016',
      name: 'Acrylic Liquid Monomer',
      description: 'Professional acrylic liquid monomer, 500ml. Used with acrylic powder for nail extensions.',
      price: 7000,
      stock: 25,
      sku: 'NL-016',
      images: ['https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-017',
      name: 'Nail Primer',
      description: 'Professional nail primer for adhesion. Prepares nails for long-lasting polish.',
      price: 4000,
      stock: 30,
      sku: 'NL-017',
      images: ['https://images.unsplash.com/photo-1596460107916-4506628f5b7e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-018',
      name: 'Nail Base Coat',
      description: 'Professional nail base coat, 100ml. Protects nails and extends polish wear.',
      price: 3000,
      stock: 35,
      sku: 'NL-018',
      images: ['https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-019',
      name: 'Nail Top Coat',
      description: 'Professional nail top coat, 100ml. High-gloss, chip-resistant finish for long wear.',
      price: 3000,
      stock: 35,
      sku: 'NL-019',
      images: ['https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'nl-020',
      name: 'Cuticle Oil',
      description: 'Professional cuticle oil, 50ml. Nourishes and moisturizes cuticles for healthy nails.',
      price: 2500,
      stock: 40,
      sku: 'NL-020',
      images: ['https://images.unsplash.com/photo-1596460107916-4506628f5b7e?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories' },
      featured: false,
      status: 'active',
    },
  ],

  // ============================================================
  // 6. EYELASHES & ACCESSORIES - 20 Unique Products
  // ============================================================
  'Eyelashes & Accessories': [
    {
      _id: 'el-001',
      name: 'Mink Eyelash Extensions',
      description: 'Premium mink eyelash extensions, 10 sets, various lengths. Natural, soft, and lightweight.',
      price: 25000,
      stock: 20,
      sku: 'EL-001',
      images: ['https://images.unsplash.com/photo-1586841559683-f84c22106e4f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'el-002',
      name: 'Faux Mink Lashes',
      description: 'High-quality faux mink lashes, 5 pairs. Cruelty-free with a natural look.',
      price: 15000,
      stock: 30,
      sku: 'EL-002',
      images: ['https://images.unsplash.com/photo-1595815771614-ade9d652e65a?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-003',
      name: 'Eyelash Extension Kit',
      description: 'Complete eyelash extension kit with tools. Everything needed for professional lash application.',
      price: 45000,
      stock: 12,
      sku: 'EL-003',
      images: ['https://images.unsplash.com/photo-1586841559683-f84c22106e4f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'el-004',
      name: 'Eyelash Glue',
      description: 'Professional eyelash extension glue, 10ml. Strong hold with safe, latex-free formula.',
      price: 5000,
      stock: 40,
      sku: 'EL-004',
      images: ['https://images.unsplash.com/photo-1595815771614-ade9d652e65a?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-005',
      name: 'Eyelash Tweezer Set',
      description: 'Professional eyelash tweezer set, 5 pieces. Precision tools for accurate lash placement.',
      price: 8000,
      stock: 25,
      sku: 'EL-005',
      images: ['https://images.unsplash.com/photo-1586841559683-f84c22106e4f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-006',
      name: 'Eyelash Primer',
      description: 'Professional eyelash extension primer, 10ml. Prepares natural lashes for better adhesion.',
      price: 3500,
      stock: 30,
      sku: 'EL-006',
      images: ['https://images.unsplash.com/photo-1595815771614-ade9d652e65a?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-007',
      name: 'Eyelash Sealer',
      description: 'Professional eyelash sealer for longevity. Locks in lashes and extends wear time.',
      price: 4000,
      stock: 28,
      sku: 'EL-007',
      images: ['https://images.unsplash.com/photo-1586841559683-f84c22106e4f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-008',
      name: 'Eyelash Remover',
      description: 'Professional eyelash extension remover, 50ml. Gentle formula for safe removal.',
      price: 6000,
      stock: 25,
      sku: 'EL-008',
      images: ['https://images.unsplash.com/photo-1595815771614-ade9d652e65a?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-009',
      name: 'Eyelash Extension Tape',
      description: 'Professional eyelash extension tape, 50 pieces. Gentle adhesive for securing under-eye pads.',
      price: 3000,
      stock: 35,
      sku: 'EL-009',
      images: ['https://images.unsplash.com/photo-1586841559683-f84c22106e4f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-010',
      name: 'Eyelash Cleaner',
      description: 'Professional eyelash extension cleaner, 100ml. Foaming cleanser for safe lash hygiene.',
      price: 3500,
      stock: 30,
      sku: 'EL-010',
      images: ['https://images.unsplash.com/photo-1595815771614-ade9d652e65a?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-011',
      name: 'Eyelash Brushes Set',
      description: 'Professional eyelash brushes, 20 pieces. Essential for cleaning and styling lashes.',
      price: 2000,
      stock: 45,
      sku: 'EL-011',
      images: ['https://images.unsplash.com/photo-1586841559683-f84c22106e4f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-012',
      name: 'Eyelash Fan Set',
      description: 'Eyelash fan set for volume lashes, 50 fans. Creates dramatic, full lash looks.',
      price: 8000,
      stock: 20,
      sku: 'EL-012',
      images: ['https://images.unsplash.com/photo-1595815771614-ade9d652e65a?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-013',
      name: 'Eyelash Nourishing Serum',
      description: 'Eyelash nourishing serum for natural lashes. Promotes growth and strengthens lashes.',
      price: 10000,
      stock: 15,
      sku: 'EL-013',
      images: ['https://images.unsplash.com/photo-1586841559683-f84c22106e4f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-014',
      name: 'Under-eye Gel Pads',
      description: 'Under-eye gel pads for lash extensions, 100 pairs. Protects and soothes under-eye area.',
      price: 4000,
      stock: 30,
      sku: 'EL-014',
      images: ['https://images.unsplash.com/photo-1595815771614-ade9d652e65a?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-015',
      name: 'Eyelash Extension Scissors',
      description: 'Professional eyelash extension scissors. Precision cutting for lash application.',
      price: 5000,
      stock: 25,
      sku: 'EL-015',
      images: ['https://images.unsplash.com/photo-1586841559683-f84c22106e4f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-016',
      name: 'Lash Storage Case',
      description: 'Professional lash extension storage case. Protects and organizes lash supplies.',
      price: 3000,
      stock: 20,
      sku: 'EL-016',
      images: ['https://images.unsplash.com/photo-1595815771614-ade9d652e65a?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-017',
      name: 'Glue Ring for Lashes',
      description: 'Professional lash extension glue ring. Holds glue securely during application.',
      price: 1500,
      stock: 40,
      sku: 'EL-017',
      images: ['https://images.unsplash.com/photo-1586841559683-f84c22106e4f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-018',
      name: 'Magnifying Mirror',
      description: 'Professional lash extension mirror with magnification. Perfect for detailed lash work.',
      price: 8000,
      stock: 15,
      sku: 'EL-018',
      images: ['https://images.unsplash.com/photo-1595815771614-ade9d652e65a?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-019',
      name: 'Premium Mascara',
      description: 'Premium mascara for natural lashes. Lengthens and volumizes with a natural finish.',
      price: 7000,
      stock: 25,
      sku: 'EL-019',
      images: ['https://images.unsplash.com/photo-1586841559683-f84c22106e4f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'el-020',
      name: 'Eyelash Curler',
      description: 'Professional eyelash curler with extra pads. Creates beautiful, natural curl.',
      price: 5000,
      stock: 30,
      sku: 'EL-020',
      images: ['https://images.unsplash.com/photo-1595815771614-ade9d652e65a?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories' },
      featured: false,
      status: 'active',
    },
  ],

  // ============================================================
  // 7. WEAVONS - 20 Unique Products
  // ============================================================
  'Weavons': [
    {
      _id: 'wv-001',
      name: 'Brazilian Weavon Bundle',
      description: 'Premium Brazilian human hair weavon, 16 inches, 3 bundles. Soft and natural texture.',
      price: 45000,
      stock: 15,
      sku: 'WV-001',
      images: ['https://images.unsplash.com/photo-1525130413817-d45c1d127c42?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'wv-002',
      name: 'Peruvian Weavon Set',
      description: 'Luxury Peruvian weavon set with closure, 18 inches. Silky, manageable, and full.',
      price: 52000,
      stock: 12,
      sku: 'WV-002',
      images: ['https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'wv-003',
      name: 'Malaysian Weavon',
      description: 'Malaysian weavon, body wave, 20 inches, 4 bundles. Long-lasting and versatile.',
      price: 48000,
      stock: 18,
      sku: 'WV-003',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-004',
      name: 'Straight Weavon Bundle',
      description: 'Silky straight weavon bundle, 14 inches. Classic, smooth, and easy to style.',
      price: 40000,
      stock: 20,
      sku: 'WV-004',
      images: ['https://images.unsplash.com/photo-1519415387722-a1c3bbef9e54?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-005',
      name: 'Curly Weavon',
      description: 'Beautiful curly weavon, 16 inches, 3 bundles. Bouncy curls with natural movement.',
      price: 46000,
      stock: 14,
      sku: 'WV-005',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-006',
      name: 'Deep Wave Weavon',
      description: 'Deep wave weavon, 18 inches, 3 bundles. Defined waves with lasting hold.',
      price: 50000,
      stock: 10,
      sku: 'WV-006',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-007',
      name: 'Body Wave Weavon',
      description: 'Body wave weavon, 20 inches, 4 bundles. Effortless waves for any occasion.',
      price: 49000,
      stock: 8,
      sku: 'WV-007',
      images: ['https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-008',
      name: 'Kinky Weavon',
      description: 'Kinky straight weavon, 14 inches, 3 bundles. Natural texture for a relaxed look.',
      price: 38000,
      stock: 22,
      sku: 'WV-008',
      images: ['https://images.unsplash.com/photo-1525130413817-d45c1d127c42?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-009',
      name: 'Water Wave Weavon',
      description: 'Water wave weavon, 16 inches, 3 bundles. Beachy waves with natural movement.',
      price: 47000,
      stock: 16,
      sku: 'WV-009',
      images: ['https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-010',
      name: 'Loose Wave Weavon',
      description: 'Loose wave weavon, 18 inches, 4 bundles. Natural, flowing waves with elegance.',
      price: 51000,
      stock: 12,
      sku: 'WV-010',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-011',
      name: 'Weavon with Closure',
      description: 'Weavon set with 4x4 closure, 16 inches. Natural part line with full volume.',
      price: 55000,
      stock: 10,
      sku: 'WV-011',
      images: ['https://images.unsplash.com/photo-1519415387722-a1c3bbef9e54?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-012',
      name: 'Weavon with Frontal',
      description: 'Weavon set with 13x4 frontal, 18 inches. Full lace front for versatile styling.',
      price: 65000,
      stock: 6,
      sku: 'WV-012',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-013',
      name: 'Ombre Weavon',
      description: 'Ombre colored weavon, 20 inches, 3 bundles. Beautiful gradient from dark to light.',
      price: 58000,
      stock: 8,
      sku: 'WV-013',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-014',
      name: 'Colored Weavon',
      description: 'Colored weavon, burgundy, 16 inches, 3 bundles. Bold and vibrant color that stands out.',
      price: 48000,
      stock: 12,
      sku: 'WV-014',
      images: ['https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-015',
      name: 'Blonde Weavon',
      description: 'Platinum blonde weavon, 18 inches, 3 bundles. Stunning blonde that catches the eye.',
      price: 54000,
      stock: 8,
      sku: 'WV-015',
      images: ['https://images.unsplash.com/photo-1525130413817-d45c1d127c42?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-016',
      name: 'Brazilian Weavon Short',
      description: 'Brazilian weavon, short length, 12 inches. Perfect for a chic, stylish look.',
      price: 35000,
      stock: 20,
      sku: 'WV-016',
      images: ['https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-017',
      name: 'Peruvian Weavon Long',
      description: 'Peruvian weavon, long length, 24 inches. Luxurious length for dramatic style.',
      price: 60000,
      stock: 8,
      sku: 'WV-017',
      images: ['https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-018',
      name: 'Malaysian Weavon Curly',
      description: 'Malaysian curly weavon, 16 inches. Beautiful curls with natural bounce.',
      price: 49000,
      stock: 14,
      sku: 'WV-018',
      images: ['https://images.unsplash.com/photo-1519415387722-a1c3bbef9e54?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-019',
      name: 'Weavon Natural Black',
      description: 'Natural black weavon, 18 inches, 3 bundles. Classic black that matches any style.',
      price: 42000,
      stock: 18,
      sku: 'WV-019',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wv-020',
      name: 'Weavon with Baby Hair',
      description: 'Weavon with pre-plucked baby hair, 16 inches. Natural hairline for a realistic look.',
      price: 52000,
      stock: 10,
      sku: 'WV-020',
      images: ['https://images.unsplash.com/photo-1553531381-41c9ea81f06d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat7', name: 'Weavons', slug: 'weavons' },
      featured: false,
      status: 'active',
    },
  ],

  // ============================================================
  // 8. TATTOOS - 20 Unique Products
  // ============================================================
  'Tattoos': [
    {
      _id: 'tt-001',
      name: 'Tattoo Machine Set',
      description: 'Professional tattoo machine set with power supply. Complete kit for artists.',
      price: 85000,
      stock: 10,
      sku: 'TT-001',
      images: ['https://images.unsplash.com/photo-1590114537015-3af78157080b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'tt-002',
      name: 'Tattoo Needles',
      description: 'Professional tattoo needles, 100 pieces, various sizes. High-quality for precise work.',
      price: 15000,
      stock: 25,
      sku: 'TT-002',
      images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-003',
      name: 'Tattoo Ink Set',
      description: 'Professional tattoo ink set, 24 colors. Vibrant pigments for stunning artwork.',
      price: 35000,
      stock: 15,
      sku: 'TT-003',
      images: ['https://images.unsplash.com/photo-1590114537015-3af78157080b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-004',
      name: 'Tattoo Transfer Paper',
      description: 'Tattoo transfer paper, 100 sheets. High-quality for stencil application.',
      price: 8000,
      stock: 30,
      sku: 'TT-004',
      images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-005',
      name: 'Tattoo Stencil Ink',
      description: 'Tattoo stencil ink for transfers, 100ml. Dark, clear transfers every time.',
      price: 6000,
      stock: 25,
      sku: 'TT-005',
      images: ['https://images.unsplash.com/photo-1590114537015-3af78157080b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-006',
      name: 'Tattoo Grip Set',
      description: 'Professional tattoo grip set, 5 pieces. Comfortable grip for extended tattooing sessions.',
      price: 12000,
      stock: 20,
      sku: 'TT-006',
      images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-007',
      name: 'Tattoo Power Supply',
      description: 'Professional tattoo power supply with LCD display. Precise voltage control.',
      price: 40000,
      stock: 12,
      sku: 'TT-007',
      images: ['https://images.unsplash.com/photo-1590114537015-3af78157080b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-008',
      name: 'Tattoo Foot Switch',
      description: 'Professional tattoo foot switch. Hands-free control for machine operation.',
      price: 15000,
      stock: 18,
      sku: 'TT-008',
      images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-009',
      name: 'Tattoo Practice Skin',
      description: 'Tattoo practice skin for training, 10 pieces. Realistic feel for perfecting skills.',
      price: 25000,
      stock: 20,
      sku: 'TT-009',
      images: ['https://images.unsplash.com/photo-1590114537015-3af78157080b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-010',
      name: 'Tattoo Wash Solution',
      description: 'Tattoo wash solution for cleaning, 500ml. Keeps work area hygienic.',
      price: 5000,
      stock: 30,
      sku: 'TT-010',
      images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-011',
      name: 'Tattoo Lubricant',
      description: 'Tattoo lubricant for smooth operation, 250ml. Reduces friction during tattooing.',
      price: 4000,
      stock: 35,
      sku: 'TT-011',
      images: ['https://images.unsplash.com/photo-1590114537015-3af78157080b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-012',
      name: 'Tattoo Aftercare Cream',
      description: 'Professional tattoo aftercare cream, 100ml. Promotes healing and protects tattoo.',
      price: 6000,
      stock: 25,
      sku: 'TT-012',
      images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-013',
      name: 'Tattoo Bandages',
      description: 'Tattoo bandages for aftercare, 50 pieces. Protects fresh tattoos from infection.',
      price: 3000,
      stock: 40,
      sku: 'TT-013',
      images: ['https://images.unsplash.com/photo-1590114537015-3af78157080b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-014',
      name: 'Tattoo Gloves',
      description: 'Professional tattoo gloves, 100 pairs. Sterile, powder-free for safety.',
      price: 5000,
      stock: 30,
      sku: 'TT-014',
      images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-015',
      name: 'Tattoo Machine Complete Set',
      description: 'Complete tattoo machine set with case. Everything needed for professional work.',
      price: 95000,
      stock: 8,
      sku: 'TT-015',
      images: ['https://images.unsplash.com/photo-1590114537015-3af78157080b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-016',
      name: 'Tattoo Needle Cartridges',
      description: 'Tattoo needle cartridges, 50 pieces. Pre-sterilized for easy use.',
      price: 12000,
      stock: 25,
      sku: 'TT-016',
      images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-017',
      name: 'Tattoo Ink Cups',
      description: 'Tattoo ink cups, 500 pieces. Small, disposable cups for ink mixing.',
      price: 3000,
      stock: 40,
      sku: 'TT-017',
      images: ['https://images.unsplash.com/photo-1590114537015-3af78157080b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-018',
      name: 'Tattoo Pigment Set',
      description: 'Professional tattoo pigment set, 12 colors. High-quality pigments for vibrant tattoos.',
      price: 28000,
      stock: 15,
      sku: 'TT-018',
      images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-019',
      name: 'Tattoo Stencil Kit',
      description: 'Complete tattoo stencil kit. Everything needed for stencil application.',
      price: 15000,
      stock: 18,
      sku: 'TT-019',
      images: ['https://images.unsplash.com/photo-1590114537015-3af78157080b?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'tt-020',
      name: 'Tattoo Cleaning Spray',
      description: 'Tattoo cleaning spray, 250ml. Sanitizes equipment between uses.',
      price: 4000,
      stock: 30,
      sku: 'TT-020',
      images: ['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat8', name: 'Tattoos', slug: 'tattoos' },
      featured: false,
      status: 'active',
    },
  ],

  // ============================================================
  // 9. WIG TOOLS - 20 Unique Products
  // ============================================================
  'Wig Tools': [
    {
      _id: 'wt-001',
      name: 'Wig Making Stand',
      description: 'Professional wig making stand with clamp. Holds wigs securely during styling.',
      price: 18000,
      stock: 20,
      sku: 'WT-001',
      images: ['https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: true,
      status: 'active',
    },
    {
      _id: 'wt-002',
      name: 'Wig Head Mannequin',
      description: 'Professional wig head mannequin with stand. Perfect for wig styling and display.',
      price: 15000,
      stock: 25,
      sku: 'WT-002',
      images: ['https://images.unsplash.com/photo-1595698199523-2c54f99aa262?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-003',
      name: 'Wig Styling Scissors',
      description: 'Professional wig styling scissors set. Precision cutting for wig maintenance.',
      price: 12000,
      stock: 18,
      sku: 'WT-003',
      images: ['https://images.unsplash.com/photo-1631561066360-4055ec316dfe?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-004',
      name: 'Wig Glue',
      description: 'Professional wig glue for application, 100ml. Strong hold for secure wig placement.',
      price: 8000,
      stock: 30,
      sku: 'WT-004',
      images: ['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-005',
      name: 'Wig Tape',
      description: 'Professional wig tape, 50 pieces. Double-sided tape for secure wig attachment.',
      price: 4000,
      stock: 35,
      sku: 'WT-005',
      images: ['https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-006',
      name: 'Wig Brush Set',
      description: 'Professional wig brush set, 5 pieces. Various brushes for wig maintenance.',
      price: 6000,
      stock: 30,
      sku: 'WT-006',
      images: ['https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-007',
      name: 'Wig Cap',
      description: 'Professional wig cap, 10 pieces. Breathable and comfortable for all-day wear.',
      price: 2000,
      stock: 50,
      sku: 'WT-007',
      images: ['https://images.unsplash.com/photo-1595698199523-2c54f99aa262?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-008',
      name: 'Wig Shampoo',
      description: 'Professional wig shampoo for cleaning, 250ml. Gentle formula for synthetic and human hair wigs.',
      price: 5000,
      stock: 25,
      sku: 'WT-008',
      images: ['https://images.unsplash.com/photo-1631561066360-4055ec316dfe?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-009',
      name: 'Wig Conditioner',
      description: 'Professional wig conditioner, 250ml. Restores moisture and shine to wigs.',
      price: 5000,
      stock: 25,
      sku: 'WT-009',
      images: ['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-010',
      name: 'Wig Stand with T-Holder',
      description: 'Professional wig stand with T-holder. Secure stand for wig styling and display.',
      price: 12000,
      stock: 15,
      sku: 'WT-010',
      images: ['https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-011',
      name: 'Wig Clips',
      description: 'Wig clips for securing, 50 pieces. Strong hold for wig stability.',
      price: 3000,
      stock: 40,
      sku: 'WT-011',
      images: ['https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-012',
      name: 'Wig Needle Set',
      description: 'Professional wig needle set, 10 pieces. Curved needles for wig making and repair.',
      price: 4000,
      stock: 30,
      sku: 'WT-012',
      images: ['https://images.unsplash.com/photo-1595698199523-2c54f99aa262?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-013',
      name: 'Wig Thread',
      description: 'Professional wig thread, 5 colors. Strong, durable thread for wig construction.',
      price: 3000,
      stock: 35,
      sku: 'WT-013',
      images: ['https://images.unsplash.com/photo-1631561066360-4055ec316dfe?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-014',
      name: 'Wig Thinner Scissors',
      description: 'Professional wig thinning scissors. Thins and texturizes wigs for a natural look.',
      price: 10000,
      stock: 15,
      sku: 'WT-014',
      images: ['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-015',
      name: 'Wig Curling Iron',
      description: 'Professional wig curling iron with temperature control. Creates beautiful curls in wigs.',
      price: 20000,
      stock: 12,
      sku: 'WT-015',
      images: ['https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-016',
      name: 'Wig Straightener',
      description: 'Professional wig straightening iron. Smooths and straightens wigs for a sleek finish.',
      price: 22000,
      stock: 10,
      sku: 'WT-016',
      images: ['https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-017',
      name: 'Wig Setting Spray',
      description: 'Professional wig setting spray, 200ml. Holds style in place for synthetic and human hair wigs.',
      price: 4000,
      stock: 25,
      sku: 'WT-017',
      images: ['https://images.unsplash.com/photo-1595698199523-2c54f99aa262?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-018',
      name: 'Wig Mannequin Set',
      description: 'Wig mannequin set with multiple heads. Ideal for wig makers and collectors.',
      price: 25000,
      stock: 8,
      sku: 'WT-018',
      images: ['https://images.unsplash.com/photo-1631561066360-4055ec316dfe?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-019',
      name: 'Wig Storage Box',
      description: 'Professional wig storage box, 2 pieces. Protects wigs from dust and damage.',
      price: 15000,
      stock: 10,
      sku: 'WT-019',
      images: ['https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
    {
      _id: 'wt-020',
      name: 'Wig Hanger Set',
      description: 'Wig hanger for storage, 5 pieces. Keeps wigs organized and tangle-free.',
      price: 3000,
      stock: 30,
      sku: 'WT-020',
      images: ['https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=400&h=400&fit=crop&crop=center'],
      category: { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools' },
      featured: false,
      status: 'active',
    },
  ],
};

// ============================================================
// CATEGORIES
// ============================================================
export const mockCategories = [
  { _id: 'cat1', name: 'Hairs', slug: 'hairs', description: 'Premium human hair and extensions', status: 'active' },
  { _id: 'cat2', name: 'Hair Products', slug: 'hair-products', description: 'Professional hair care products', status: 'active' },
  { _id: 'cat3', name: 'Salon Materials', slug: 'salon-materials', description: 'Professional salon supplies', status: 'active' },
  { _id: 'cat4', name: 'Salon Equipment', slug: 'salon-equipment', description: 'Professional salon equipment', status: 'active' },
  { _id: 'cat5', name: 'Nails & Accessories', slug: 'nails-accessories', description: 'Nail care and accessories', status: 'active' },
  { _id: 'cat6', name: 'Eyelashes & Accessories', slug: 'eyelashes-accessories', description: 'Eyelash extensions and accessories', status: 'active' },
  { _id: 'cat7', name: 'Weavons', slug: 'weavons', description: 'Quality weavon and hair extensions', status: 'active' },
  { _id: 'cat8', name: 'Tattoos', slug: 'tattoos', description: 'Tattoo supplies and equipment', status: 'active' },
  { _id: 'cat9', name: 'Wig Tools', slug: 'wig-tools', description: 'Wig making and styling tools', status: 'active' },
];

// ============================================================
// HELPER FUNCTIONS
// ============================================================
export const getAllProducts = () => {
  const allProducts = [];
  for (const category in mockProducts) {
    allProducts.push(...mockProducts[category]);
  }
  return allProducts;
};

export const getProductsByCategory = (categorySlug) => {
  for (const [catName, products] of Object.entries(mockProducts)) {
    const slug = catName.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-');
    if (slug === categorySlug) {
      return products;
    }
  }
  return [];
};

export const getProductById = (id) => {
  const allProducts = getAllProducts();
  return allProducts.find(p => p._id === id);
};